### ISSUE TITLE
A little more self-descriptive field names?

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/altimetry#1]
A minor thing, but why not use altimetry as prefix and why not expand the instrument fields to altimetry:instrument_type and altimetry:instrument_mode ? :-)

**Comment by emmanuelmathot** [comment]
Maybe because of an old programmer habit to save bytes in documents... ;-)
If you think this is a bit penny-pinching, then I will set all names properly.

**Comment by m-mohr** [comment]
I'd at least expand the field name parts without prefix (inst_...), I don't care so much for the prefix. Maybe that's a good middleground?
